package es.gamingtroop.reader

// Generated Spanish fallback for non-Android model tests. Keep aligned with values/strings.xml.
internal val defaultTexts = mapOf(
    R.string.books_lower to "libros", R.string.volumes_lower to "tomos", R.string.page_word to "Página",
    R.string.tr_000 to "Usa una dirección HTTPS sin claves ni parámetros",
    R.string.tr_001 to "Usuario o contraseña no válidos",
    R.string.tr_002 to "No se pudo iniciar sesión (HTTP %1\$s)",
    R.string.tr_003 to "Respuesta de inicio de sesión incompatible",
    R.string.tr_004 to "Vuelve a iniciar sesión para sincronizar",
    R.string.tr_005 to "La cuenta cambió. Vuelve a iniciar sesión.",
    R.string.tr_006 to "Vuelve a iniciar sesión para recuperar el permiso de imágenes. Se conservan las descargas.",
    R.string.tr_010 to "Sesión caducada: vuelve a entrar. Tus descargas y progreso siguen guardados.",
    R.string.tr_011 to "La app aún no es compatible con la autenticación de imágenes de este Kavita (HTTP 400 · %1\$s). No borres la cola: el contenido y el progreso se conservan.",
    R.string.tr_012 to "Es necesario iniciar sesión",
    R.string.tr_013 to "Tu cuenta no tiene permiso para esta operación",
    R.string.tr_014 to "El contenido ya no está disponible",
    R.string.tr_015 to "Solicitud no compatible con Kavita (HTTP 400 · %1\$s)",
    R.string.tr_016 to "Error del servidor (HTTP %1\$s)",
    R.string.tr_017 to "Descarga cancelada",
    R.string.tr_018 to "Se ha alcanzado el límite de tamaño de esta descarga",
    R.string.tr_019 to "No queda espacio suficiente",
    R.string.tr_020 to "Recurso vacío",
    R.string.tr_021 to "No se pudo guardar la descarga",
    R.string.tr_022 to "Actualizaciones de la app",
    R.string.tr_023 to "No se pudo comprobar la nueva versión. Comprueba la conexión y vuelve a intentarlo.",
    R.string.tr_024 to "Actualización sustituida",
    R.string.tr_025 to "No hay espacio suficiente para la actualización",
    R.string.tr_026 to "Descarga interrumpida. Puedes reintentar; tus lecturas siguen intactas.",
    R.string.tr_027 to "El archivo no es una APK válida",
    R.string.tr_028 to "La APK no corresponde a la actualización publicada",
    R.string.tr_029 to "Esta versión requiere un Android más reciente",
    R.string.tr_030 to "La firma de esta APK no coincide con la app instalada",
    R.string.tr_031 to "No hay una actualización disponible",
    R.string.tr_032 to "La APK ya no está disponible o no es válida. Vuelve a descargarla.",
    R.string.tr_033 to "Hay una actualización más reciente. Vuelve a abrir el instalador.",
    R.string.tr_035 to "Actualización lista · toca para instalar",
    R.string.tr_036 to "Nueva versión disponible",
    R.string.tr_037 to "API Bigme no encontrada",
    R.string.tr_038 to "API Bigme no compatible",
    R.string.tr_039 to "Acceso al refresco Bigme bloqueado",
    R.string.tr_040 to "API Bigme detectada · experimental",
    R.string.tr_041 to "La solicitud Bigme falló; se usa repintado compatible",
    R.string.tr_042 to "Preparando voz…",
    R.string.tr_043 to "Voz sin conexión · %1\$s",
    R.string.tr_044 to "No hay una voz sin conexión instalada. Añádela en los ajustes de voz de Android.",
    R.string.tr_045 to "No hay un motor de voz disponible. Puedes configurarlo en Android.",
    R.string.tr_047 to "No se pudo reproducir la voz. Comprueba el motor de Android.",
    R.string.tr_048 to "Otra aplicación está usando el audio. Vuelve a intentarlo.",
    R.string.tr_049 to "Fin del libro. Puedes marcarlo como terminado en el lector.",
    R.string.tr_050 to "Esperando descarga de la siguiente sección. Reanuda cuando esté disponible.",
    R.string.tr_051 to "El motor de voz no pudo reproducir este párrafo.",
    R.string.tr_052 to "No se puede leer esta sección. Comprueba la descarga del libro.",
    R.string.tr_053 to "Temporizador terminado",
    R.string.tr_054 to "Respuesta de marcadores incompatible",
    R.string.tr_055 to "Este marcador también cambió o se eliminó en Kavita. No se ha sobrescrito.",
    R.string.tr_056 to "Kavita no confirmó la eliminación del marcador. El cambio local sigue pendiente.",
    R.string.tr_057 to "Kavita no confirmó el marcador del móvil. Se reintentará sin perderlo.",
    R.string.tr_058 to "La edición cambió. Marcadores conservados sin moverlos a otro archivo.",
    R.string.tr_059 to "Marcador de otra edición; se conserva sin sincronizar.",
    R.string.tr_060 to "Kavita no confirmó la eliminación del marcador",
    R.string.tr_061 to "Kavita no confirmó el nuevo marcador",
    R.string.tr_062 to "Página %1\$s",
    R.string.tr_063 to "No se pudieron sincronizar los marcadores. Se conservan en este móvil.",
    R.string.tr_064 to "Tomo",
    R.string.tr_065 to "Tomo %1\$s",
    R.string.tr_066 to "%1\$s · Parte %2\$s",
    R.string.tr_067 to "Libro",
    R.string.tr_069 to " · Parte",
    R.string.tr_070 to "Tomo ",
    R.string.tr_071 to "Lectura continua lista",
    R.string.tr_072 to "Preparando lectura",
    R.string.tr_073 to "No se puede abrir la página %1\$s. Vuelve a descargar este tomo.",
    R.string.tr_074 to "No se pudo mostrar esta página. Prueba el modo Página completa.",
    R.string.tr_075 to "Fin del tomo",
    R.string.tr_076 to "Esperando más páginas",
    R.string.tr_077 to "El tomo se marca leído al pulsar Terminado; no al cargar la última imagen.",
    R.string.tr_078 to "%1\$s/%2\$s disponibles · %3\$s",
    R.string.tr_079 to "Terminado · continuar",
    R.string.tr_080 to "Kavita no devolvió una carátula válida",
    R.string.tr_081 to "No se pudo guardar la carátula",
    R.string.tr_082 to "No se pudo cargar la carátula. Comprueba la conexión.",
    R.string.tr_083 to "Sin carátula · %1\$s",
    R.string.tr_084 to "Carátula · %1\$s",
    R.string.tr_086 to "No se pudo consultar esta obra. Puedes reintentar.",
    R.string.tr_087 to "Novedades de tus series",
    R.string.tr_088 to "Novedades en tus series",
    R.string.tr_089 to "%1\$s nuevos archivos de lectura · toca para verlos",
    R.string.tr_090 to "Siguiente tomo pendiente: tamaño desconocido o límite de espacio alcanzado. Puedes descargarlo manualmente.",
    R.string.tr_091 to "Siguiente tomo preparado · %1\$s archivos en cola",
    R.string.tr_092 to "Tipo de pantalla",
    R.string.tr_093 to "Texto negro, fondo blanco y controles estáticos. Hoja y lectura continua quedan suspendidos, sin borrar tus ajustes.",
    R.string.tr_094 to "Limpiar al navegar",
    R.string.tr_095 to "Refresco Bigme experimental",
    R.string.tr_096 to "Solicita limpieza al controlador Bigme. Actívalo y prueba «Limpiar pantalla ahora». Desactívalo si no mejora. Se desactiva tras cambiar el firmware.",
    R.string.tr_097 to "Refresco Bigme solicitado al navegar; pendiente de comprobar en tu pantalla.",
    R.string.tr_098 to "Controlador BOOX detectado; falta comprobar el refresco en el panel.",
    R.string.tr_099 to "Repintado compatible. Activa también el refresco completo en los ajustes del lector.",
    R.string.tr_100 to "Limpiar pantalla ahora",
    R.string.tr_101 to "Compatibilidad y refresco",
    R.string.tr_102 to "Refresco de tinta electrónica",
    R.string.tr_103 to "La limpieza produce un destello deliberado y añade espera. Se realiza al terminar cada navegación o desplazamiento, no durante el gesto. Puedes desactivarla sin quitar el tema.",
    R.string.tr_104 to "Controlador no disponible",
    R.string.tr_105 to "Se usa la orden de limpieza global Bigme con el modo indicado por su firmware. La API está documentada por la comunidad en otro Bigme; no se ha validado aún en B751C S con sistema 1.7.0. Que acepte la orden no prueba que elimine el ghosting.",
    R.string.tr_106 to "Se solicitará refresco completo al controlador BOOX. El resultado depende del firmware y debe comprobarse en el lector.",
    R.string.tr_107 to "No está activo un controlador nativo compatible. Se repinta toda la ventana con un ciclo negro/blanco; no garantiza un refresco físico. Activa también el refresco completo por página en los ajustes de tu lector.",
    R.string.tr_108 to "Puedes exportar el estado de detección desde Mi espacio → Diagnóstico. No incluye número de serie ni datos de la cuenta.",
    R.string.tr_109 to "Usa Calidad/Normal para texto e imágenes; A2/Rápido puede dejar más residuos. La app no controla el teclado ni los diálogos de Android. No cambia brillo ni ajustes globales.",
    R.string.tr_110 to "Se conservan los colores originales. Resolución, contraste y tiempos de refresco dependen del panel; no todos los dispositivos de color usan el mismo controlador.",
    R.string.tr_111 to "Entendido",
    R.string.tr_112 to "Sí ✓",
    R.string.tr_113 to "No",
    R.string.tr_115 to "Cerrar",
    R.string.tr_116 to "Pantalla normal",
    R.string.tr_117 to "Tinta electrónica B/N",
    R.string.tr_118 to "Tinta electrónica color",
    R.string.tr_119 to "No se encuentra el libro",
    R.string.tr_120 to "# Notas de Troop Reader\n\n",
    R.string.tr_121 to " · sección ",
    R.string.tr_123 to "No se pudo buscar en el libro descargado.",
    R.string.tr_124 to "Espera a que la sección esté lista.",
    R.string.tr_125 to "Mantén pulsado el texto y selecciona un fragmento de un párrafo antes de añadir una nota.",
    R.string.tr_126 to "Diccionario",
    R.string.tr_127 to "Palabra o texto seleccionado",
    R.string.tr_128 to "Elige una aplicación instalada para consultar solo este fragmento. Su disponibilidad offline depende de los diccionarios que tenga descargados.",
    R.string.tr_129 to "No hay aplicaciones compatibles instaladas. Instala un diccionario con la acción Procesar texto de Android.",
    R.string.tr_130 to "No se pudo abrir este diccionario.",
    R.string.tr_131 to "No se pudieron exportar las notas.",
    R.string.tr_132 to "Buscar en este libro",
    R.string.tr_133 to "Texto a buscar",
    R.string.tr_134 to "Escribe al menos dos caracteres. Busca en todas las secciones descargadas.",
    R.string.tr_135 to "%1\$s coincidencias",
    R.string.tr_136 to " · se muestran las primeras 200",
    R.string.tr_137 to "Sección %1\$s",
    R.string.tr_138 to "Subrayados y notas",
    R.string.tr_139 to "Selecciona texto en el libro y elige «Subrayar / Nota», o usa esa acción en Herramientas.",
    R.string.tr_140 to "Nota de otra edición",
    R.string.tr_141 to "Ir",
    R.string.tr_142 to "Editar nota",
    R.string.tr_143 to "Eliminar",
    R.string.tr_144 to "Exportar notas",
    R.string.tr_145 to "Lectura en voz alta",
    R.string.tr_146 to "Velocidad · %.2f×",
    R.string.tr_147 to "Temporizador",
    R.string.tr_148 to "Sin límite",
    R.string.tr_150 to "Pausar",
    R.string.tr_151 to "Reanudar",
    R.string.tr_152 to "Leer desde aquí",
    R.string.tr_153 to "Desde el inicio de sección",
    R.string.tr_154 to "Usa una voz instalada sin conexión. Avanza por las secciones del libro; no lo marca como terminado. Continúa con la pantalla apagada. Usa la notificación o los auriculares para pausar. Se pausa al perder el audio o desconectar auriculares.",
    R.string.tr_155 to "Abre Ajustes de Android → Texto a voz para instalar una voz.",
    R.string.tr_156 to "Ajustes de voz de Android",
    R.string.tr_157 to "Volver al libro",
    R.string.tr_158 to "Guardar subrayado y nota",
    R.string.tr_159 to "Nota opcional",
    R.string.tr_160 to "Guardar",
    R.string.tr_161 to "Cancelar",
    R.string.tr_162 to "Herramientas del libro",
    R.string.tr_163 to "Aceptar",
    R.string.tr_164 to "Tu biblioteca.\nTambién sin conexión.",
    R.string.tr_165 to "TROOP READER · PARA KAVITA",
    R.string.tr_166 to "Servidor Kavita",
    R.string.tr_167 to "Usuario",
    R.string.tr_168 to "Contraseña",
    R.string.tr_169 to "No se pudo conectar de forma segura. Comprueba servidor y conexión.",
    R.string.tr_170 to "Entrar en mi biblioteca",
    R.string.tr_171 to "App independiente · Versión de prueba\nTu contraseña no se guarda. Las descargas quedan en este dispositivo.",
    R.string.tr_172 to "Ver demostración sin cuenta",
    R.string.tr_173 to "No se pudo conectar. Lo descargado sigue disponible.",
    R.string.tr_174 to "No se pudo cargar Kavita. Tus descargas siguen disponibles; puedes reintentar.",
    R.string.tr_175 to "No se pudo consultar Kavita. Se muestra el catálogo guardado.",
    R.string.tr_178 to "Actualizar biblioteca",
    R.string.tr_179 to "Ajustes",
    R.string.tr_180 to "Biblioteca",
    R.string.tr_181 to "Descargas",
    R.string.tr_182 to "Progreso",
    R.string.tr_183 to "Mi espacio",
    R.string.tr_184 to "Demostración · datos de ejemplo",
    R.string.tr_185 to "Sin conexión · tus descargas siguen disponibles",
    R.string.tr_186 to "Buscar en la biblioteca",
    R.string.tr_187 to "Todo",
    R.string.tr_188 to "Continúa donde lo dejaste",
    R.string.tr_189 to "Disponible sin conexión",
    R.string.tr_190 to "Lectura parcial · %1\$s/%2\$s",
    R.string.tr_191 to "Sin resultados",
    R.string.tr_192 to "Tu biblioteca aparecerá aquí",
    R.string.tr_193 to "Prueba otro título o cambia el filtro de biblioteca.",
    R.string.tr_194 to "Conéctate a Kavita y pulsa actualizar. Las descargas no requieren conexión.",
    R.string.tr_195 to "Descargado",
    R.string.tr_197 to "Ver %1\$s",
    R.string.tr_198 to "Descargar más",
    R.string.tr_199 to "Progreso de lectura",
    R.string.tr_200 to "Prioridad: cambios de este móvil",
    R.string.tr_201 to "Prioridad: revisar conflictos",
    R.string.tr_202 to "Última comprobación: %1\$s",
    R.string.tr_203 to "Sincronizar ahora",
    R.string.tr_204 to "Sin cambios pendientes",
    R.string.tr_205 to "Puedes seguir leyendo sin cobertura. Tu avance se guardará aquí hasta reconectar.",
    R.string.tr_206 to "Lectura %1\$s",
    R.string.tr_207 to "Tu copia local y tu progreso se conservan.",
    R.string.tr_208 to "Marcadores · %1\$s",
    R.string.tr_209 to "Marcador · %1\$s",
    R.string.tr_210 to "Eliminación pendiente",
    R.string.tr_211 to "Guardado en el móvil · pendiente de sincronizar",
    R.string.tr_212 to "La API no informa de la fecha de edición. No elegimos una versión por su hora de descarga.",
    R.string.tr_213 to "Conservar ambos",
    R.string.tr_214 to "Conservar Kavita",
    R.string.tr_215 to "Deshacer eliminación",
    R.string.tr_216 to "En Kavita: %1\$s",
    R.string.tr_217 to "Pendiente de enviar",
    R.string.tr_218 to "En este móvil: %1\$s · %2\$s",
    R.string.tr_219 to "También cambió en otro dispositivo. Elige qué posición conservar.",
    R.string.tr_220 to "Conservar la del móvil",
    R.string.tr_221 to "Conservar la de Kavita",
    R.string.tr_222 to "Catálogo guardado · abre los %1\$s descargados",
    R.string.tr_223 to "Elige %1\$s para leer sin conexión",
    R.string.tr_224 to "Quitar selección",
    R.string.tr_225 to "Seleccionar todos los %1\$s",
    R.string.tr_226 to "Descargar (%1\$s)",
    R.string.tr_227 to "Los ya descargados no se repiten.",
    R.string.tr_228 to "Preparación detenida. Lo añadido sigue en Descargas.",
    R.string.tr_229 to "Detener preparación del lote",
    R.string.tr_230 to "Reintentar conexión",
    R.string.tr_231 to "%1\$s páginas/secciones",
    R.string.tr_232 to " · %1\$s partes",
    R.string.tr_233 to "Leer",
    R.string.tr_234 to "Leer disponible",
    R.string.tr_235 to "Seleccionar %1\$s",
    R.string.tr_236 to "No hay %1\$s cargados. Si estás offline, abre Descargas.",
    R.string.tr_237 to "Descargar selección",
    R.string.tr_238 to "%1\$s %2\$s · %3\$s páginas/secciones. Se guardarán de uno en uno. ",
    R.string.tr_239 to "Esperarán a una red sin límite de datos. ",
    R.string.tr_240 to "Pueden usar datos móviles. ",
    R.string.tr_241 to "El tamaño final depende de las imágenes y recursos. Puedes pausar cada descarga.",
    R.string.tr_242 to "%1\$s %2\$s preparados · %3\$s archivos en cola",
    R.string.tr_243 to "%1\$s archivos no preparados: ",
    R.string.tr_245 to "No se completó el lote. Revisa Descargas antes de reintentar.",
    R.string.tr_246 to "Añadir a descargas",
    R.string.tr_247 to "versión no informada",
    R.string.tr_249 to "Descargar solo por Wi‑Fi",
    R.string.tr_250 to "Solo Wi-Fi",
    R.string.tr_251 to "Carátulas: %1\$s avisos",
    R.string.tr_252 to "Espacio libre en el móvil: %1\$s",
    R.string.tr_253 to "Solo Wi‑Fi usa redes sin límite de datos. El cambio se aplica también a las descargas pendientes, sin borrar la cola. Las pausadas manualmente seguirán pausadas. El progreso sí se sincroniza por datos. Android puede retrasar el trabajo en segundo plano.",
    R.string.tr_254 to "Dar prioridad a este móvil",
    R.string.tr_255 to "Prioridad de este móvil",
    R.string.tr_256 to "Los cambios pendientes de lectura y marcadores de esta app sustituyen a los de Kavita, aunque la web haya avanzado más. Sin cambios locales, se reciben los de la web.",
    R.string.tr_257 to "Si cambias una lectura o marcador también en la web, revisa el conflicto antes de sustituirlo.",
    R.string.tr_258 to "Se aplica a las siguientes operaciones de sincronización.",
    R.string.tr_259 to "Cerrar sesión",
    R.string.tr_260 to "Listo",
    R.string.tr_261 to "Las descargas y %1\$s avances pendientes se conservarán para esta cuenta. Inicia sesión de nuevo con el mismo usuario para acceder a ellos.",
    R.string.tr_268 to "Pendiente",
    R.string.tr_269 to "Eliminado del dispositivo",
    R.string.tr_270 to "Sin sincronizar",
    R.string.tr_271 to "Recurso EPUB no válido",
    R.string.tr_272 to "Ruta de recurso EPUB no compatible",
    R.string.tr_273 to "El libro contiene recursos externos no descargables de forma segura",
    R.string.tr_274 to "Falta la ruta del recurso",
    R.string.tr_275 to "Demasiados recursos enlazados en el EPUB",
    R.string.tr_276 to "No se pudo guardar el recurso del libro",
    R.string.tr_278 to "Lectura reciente",
    R.string.tr_279 to "Título A–Z",
    R.string.tr_280 to "Mayor tamaño",
    R.string.tr_281 to "Todas",
    R.string.tr_282 to "En lectura",
    R.string.tr_283 to "Pendientes",
    R.string.tr_284 to "Descargas leídas",
    R.string.tr_285 to "Todos los tipos",
    R.string.tr_286 to "No se pudo completar la operación. Las demás descargas y tu progreso se conservan.",
    R.string.tr_287 to "← Todas las obras",
    R.string.tr_288 to "Tu biblioteca offline",
    R.string.tr_289 to "%1\$s obras · %2\$s",
    R.string.tr_290 to "%1\$s %2\$s · %3\$s leídos",
    R.string.tr_291 to "Buscar en descargas",
    R.string.tr_292 to "Se refiere a lo descargado, no a toda la serie en Kavita.",
    R.string.tr_293 to "Liberar leídos · %1\$s",
    R.string.tr_294 to "Eliminar todas las descargas",
    R.string.tr_295 to "Eliminar obras (%1\$s)",
    R.string.tr_296 to "Cola · %1\$s pendientes",
    R.string.tr_297 to "Ocultar cola",
    R.string.tr_298 to "Ver cola",
    R.string.tr_299 to "Seleccionar toda la cola",
    R.string.tr_300 to "Vaciar cola",
    R.string.tr_301 to "Pausar toda la cola",
    R.string.tr_302 to "Pausar selección",
    R.string.tr_303 to "Reintentar pendientes",
    R.string.tr_304 to "Reanudar (%1\$s)",
    R.string.tr_305 to "Quitar (%1\$s)",
    R.string.tr_306 to "Seleccionar descarga %1\$s · %2\$s",
    R.string.tr_307 to "Sin obras descargadas",
    R.string.tr_308 to "No hay coincidencias",
    R.string.tr_309 to "Descarga desde Biblioteca. Los originales permanecen en Kavita.",
    R.string.tr_310 to "Prueba otro título, tipo o estado de lectura.",
    R.string.tr_311 to "Limpiar filtros",
    R.string.tr_312 to "Seleccionar obra %1\$s",
    R.string.tr_314 to "Eliminar del móvil",
    R.string.tr_315 to "Leer / continuar obra",
    R.string.tr_316 to "Seleccionar todos",
    R.string.tr_317 to "Eliminar selección (%1\$s)",
    R.string.tr_318 to "Eliminar toda la obra",
    R.string.tr_319 to "Solo pendientes de leer",
    R.string.tr_320 to "Todos los tomos o libros descargados están leídos.",
    R.string.tr_321 to "Descarga incompleta",
    R.string.tr_322 to "Releer",
    R.string.tr_323 to "Pausar descarga",
    R.string.tr_324 to "Reintentar descarga",
    R.string.tr_325 to "Marcar sin leer",
    R.string.tr_326 to "Marcar leído",
    R.string.tr_327 to "¿Quitar %1\$s descargas de la cola?",
    R.string.tr_328 to "¿Eliminar solo la descarga?",
    R.string.tr_329 to "Se borrarán los archivos parciales seleccionados, no las descargas completas. El progreso y los marcadores se conservan.",
    R.string.tr_330 to "Se eliminarán %1\$s archivos de lectura del móvil, incluidas las descargas completas seleccionadas. Los originales de Kavita, tu progreso y tus marcadores se conservan.",
    R.string.tr_331 to "Quitar de la cola",
    R.string.tr_332 to "Eliminar descarga",
    R.string.tr_333 to "Favorita",
    R.string.tr_334 to "Siguiendo",
    R.string.tr_335 to "Seguir novedades",
    R.string.tr_336 to "Añadir a colección",
    R.string.tr_337 to "Colecciones · %1\$s",
    R.string.tr_338 to "Nueva colección",
    R.string.tr_339 to "Crear y añadir",
    R.string.tr_340 to "No se pudo abrir o guardar el archivo. Tus datos siguen intactos.",
    R.string.tr_341 to "Copia guardada. No contiene contraseña ni archivos de libros.",
    R.string.tr_342 to "Notas exportadas en Markdown.",
    R.string.tr_343 to "Diagnóstico exportado. No se ha enviado automáticamente.",
    R.string.tr_344 to "Favoritos",
    R.string.tr_345 to "Colecciones",
    R.string.tr_346 to "Novedades",
    R.string.tr_347 to "Estadísticas",
    R.string.tr_348 to "Copias y notas",
    R.string.tr_349 to "Kavita",
    R.string.tr_350 to "Diagnóstico",
    R.string.tr_351 to "Diagnóstico técnico",
    R.string.tr_352 to "Versión, Android, recuentos de descargas y códigos HTTP. No incluye cuenta, servidor, títulos, textos, notas, claves ni registros completos.",
    R.string.tr_353 to "Exportar diagnóstico",
    R.string.tr_354 to "Marca una obra como favorita desde Ver tomos/libros. Aquí tendrás acceso directo a ella.",
    R.string.tr_355 to "Abrir obra",
    R.string.tr_356 to "Nombre de la colección",
    R.string.tr_357 to "Crear colección",
    R.string.tr_358 to "Eliminar colección %1\$s",
    R.string.tr_359 to "Añade obras desde su catálogo.",
    R.string.tr_360 to "Quitar %1\$s de la colección",
    R.string.tr_361 to "Sigue una obra desde su catálogo. Se comprueba al abrir y aproximadamente cada 12 horas; Android puede aplazarlo.",
    R.string.tr_362 to "%1\$s novedades detectadas",
    R.string.tr_363 to "Comprobación terminada. Revisa los avisos de cada obra.",
    R.string.tr_364 to "No se pudo comprobar Kavita. Reintenta cuando tengas conexión.",
    R.string.tr_365 to "Buscar novedades",
    R.string.tr_366 to "Todavía no sigues ninguna obra.",
    R.string.tr_367 to "Pendiente de primera comprobación",
    R.string.tr_368 to "%1\$s archivos nuevos sin revisar",
    R.string.tr_370 to "Y %1\$s más…",
    R.string.tr_371 to "Ver obra",
    R.string.tr_372 to "Marcar novedades vistas",
    R.string.tr_373 to "Dejar de seguir",
    R.string.tr_374 to "Guardar estadísticas en este móvil",
    R.string.tr_375 to "%1\$s min de lectura",
    R.string.tr_376 to "%1\$s páginas/secciones visitadas",
    R.string.tr_377 to "%1\$s lecturas completadas · %2\$s días con actividad",
    R.string.tr_378 to "Cuenta desde esta versión, solo con el lector abierto y visible. Visitar una página no certifica haberla leído.",
    R.string.tr_379 to "%1\$s · %2\$s min · %3\$s páginas/secciones",
    R.string.tr_380 to "Borrar estadísticas",
    R.string.tr_381 to "Copia de lectura",
    R.string.tr_382 to "Guarda progreso, marcadores, notas, favoritos, colecciones y ajustes. Para restaurar en otro móvil, inicia sesión con la misma cuenta. No incluye contraseñas ni descargas: los libros se descargan de nuevo.",
    R.string.tr_383 to "Exportar copia",
    R.string.tr_384 to "Restaurar copia",
    R.string.tr_385 to "%1\$s subrayados y notas guardados",
    R.string.tr_386 to "Exportar notas en Markdown",
    R.string.tr_387 to "La copia contiene tus títulos y anotaciones. Elige dónde guardarla con el selector de archivos de Android.",
    R.string.tr_388 to "Eliminar colección",
    R.string.tr_389 to "Se elimina «%1\$s», no sus libros ni su progreso.",
    R.string.tr_390 to "Se elimina el historial estadístico local. Tu progreso y marcadores no cambian.",
    R.string.tr_391 to "Borrar",
    R.string.tr_392 to "Restaurar datos de lectura",
    R.string.tr_393 to "%1\$s archivos de lectura, %2\$s marcadores y %3\$s notas. Se añadirán los datos que falten; se conservan tus posiciones, notas y descargas actuales. El progreso recuperado queda pendiente de comprobar con Kavita.",
    R.string.tr_394 to "Copia restaurada. Revisa Progreso; las descargas actuales se conservan.",
    R.string.tr_395 to "Restaurar",
    R.string.tr_396 to "No se pudo aplicar el ajuste",
    R.string.tr_397 to "Siguiente tomo sin esperas",
    R.string.tr_398 to "Preparar el siguiente tomo al leer",
    R.string.tr_399 to "Automáticas solo por Wi‑Fi",
    R.string.tr_400 to "Espacio máximo para descargas automáticas",
    R.string.tr_402 to "No borra libros ni reanuda tomos pausados. El límite solo cuenta archivos descargados automáticamente; al alcanzarlo se detiene. Si el ajuste general exige Wi‑Fi, también se respeta aquí.",
    R.string.tr_403 to "Subrayar / Nota",
    R.string.tr_405 to "Ir a sección",
    R.string.tr_406 to "Ir a página",
    R.string.tr_407 to "Cerrar selector",
    R.string.tr_408 to "Páginas",
    R.string.tr_409 to "Buscar tomos o libros",
    R.string.tr_410 to "Borrar filtro",
    R.string.tr_411 to "Buscar %1\$s",
    R.string.tr_412 to "Sin resultados en el catálogo guardado",
    R.string.tr_413 to "Actual · ",
    R.string.tr_414 to "%1\$s/%2\$s partes descargadas",
    R.string.tr_415 to "Descarga parcial · puedes empezar a leer",
    R.string.tr_416 to "Sin descargar",
    R.string.tr_417 to "Parte %1\$s",
    R.string.tr_418 to "Leído",
    R.string.tr_419 to "Página %1\$s / %2\$s",
    R.string.tr_420 to "Ver %1\$s / Descargar más",
    R.string.tr_421 to "Este libro no incluye índice. Puedes elegir una sección.",
    R.string.tr_422 to " · Actual",
    R.string.tr_423 to "Toca una miniatura para ir a esa página",
    R.string.tr_424 to "Vista previa de página %1\$s",
    R.string.tr_425 to "El EPUB tiene %1\$s secciones; su paginación cambia con la letra.",
    R.string.tr_426 to "Elige una página entre 1 y %1\$s.",
    R.string.tr_427 to "Número de sección",
    R.string.tr_428 to "Número de página",
    R.string.tr_429 to "Introduce un número entre 1 y %1\$s",
    R.string.tr_430 to "No se encuentra esta página",
    R.string.tr_431 to "Esta sección aún no está descargada",
    R.string.tr_432 to "Tu progreso sigue guardado. Reintenta la descarga desde Biblioteca.",
    R.string.tr_433 to "%1\$s/%2\$s disponibles · %3\$s. Conservamos tu posición mientras continúa la descarga.",
    R.string.tr_434 to "Leer lo disponible",
    R.string.tr_435 to "Volver a Descargas",
    R.string.tr_436 to "Volver",
    R.string.tr_437 to "Buscar en el libro",
    R.string.tr_438 to "Marcadores",
    R.string.tr_439 to "Tomos y páginas",
    R.string.tr_440 to "Opciones de lectura",
    R.string.tr_441 to "%1\$s/%2\$s descargadas · puedes seguir leyendo lo disponible",
    R.string.tr_442 to "Anterior →",
    R.string.tr_443 to "← Anterior",
    R.string.tr_446 to "← Siguiente",
    R.string.tr_447 to "Siguiente →",
    R.string.tr_448 to "Terminado",
    R.string.tr_449 to "Página lista",
    R.string.tr_450 to "Cargando página",
    R.string.tr_451 to "Lectura. Toca el centro para mostrar controles y los bordes para pasar página.",
    R.string.tr_452 to "Lectura. Toca para mostrar controles. Desliza para pasar página; con zoom, desde un extremo de la imagen.",
    R.string.tr_454 to "Guardar ajustes solo para esta obra",
    R.string.tr_455 to "Los cambios de lectura se recuerdan para %1\$s. Las demás obras conservan sus ajustes.",
    R.string.tr_456 to "Se están usando los ajustes generales. Activa esta opción para personalizar solo esta obra.",
    R.string.tr_457 to "Modo de lectura",
    R.string.tr_458 to "Página completa",
    R.string.tr_459 to "Ajustar al ancho",
    R.string.tr_460 to "Doble página",
    R.string.tr_461 to "Vertical continuo",
    R.string.tr_462 to "Continuar con el siguiente tomo/libro",
    R.string.tr_463 to "Cambiar de %1\$s",
    R.string.tr_464 to "%1\$s anterior",
    R.string.tr_465 to "%1\$s siguiente",
    R.string.tr_466 to "Cambiar de tomo no marca el actual como terminado ni salta tomos que falten por descargar.",
    R.string.tr_467 to "Pasar página",
    R.string.tr_468 to "Arrastrando",
    R.string.tr_469 to "Toque en los bordes",
    R.string.tr_470 to "Desliza verticalmente para leer. Si eliges los bordes, estos saltan al inicio de la página anterior o siguiente. El centro muestra los controles.",
    R.string.tr_471 to "Toca el borde izquierdo o derecho para pasar página, también con zoom. Toca el centro para mostrar u ocultar controles. Arrastra para mover la imagen ampliada.",
    R.string.tr_472 to "Desliza horizontalmente para pasar página. Con zoom, arrastra para recorrer la imagen; desde un extremo, vuelve a deslizar hacia fuera para cambiar de página. Toca para mostrar u ocultar controles.",
    R.string.tr_473 to "Los bordes responden al soltar el dedo. Amplía con la pinza o con doble toque en el centro. Se respeta la dirección de lectura del manga.",
    R.string.tr_474 to "Efecto de paso de página",
    R.string.tr_475 to "Sin efecto",
    R.string.tr_476 to "Hoja",
    R.string.tr_477 to "El efecto Hoja se aplica solo al lector paginado. Tu elección se conserva al volver a ese modo.",
    R.string.tr_478 to "Hoja simula el pliegue al avanzar o retroceder, por arrastre o toque y también con zoom. Si Android desactiva las animaciones, se pasa sin efecto.",
    R.string.tr_479 to "Pasar página con volumen",
    R.string.tr_480 to "Volumen − avanza; volumen + retrocede. Durante la voz o con un diálogo abierto, los botones siguen controlando el audio.",
    R.string.tr_481 to "Orientación",
    R.string.tr_482 to "Automática",
    R.string.tr_483 to "Vertical",
    R.string.tr_484 to "Horizontal",
    R.string.tr_485 to "Tema",
    R.string.tr_486 to "Noche",
    R.string.tr_487 to "Sepia",
    R.string.tr_488 to "Día",
    R.string.tr_489 to "Tamaño de letra · %1\$s",
    R.string.tr_490 to "Interlineado · %.1f",
    R.string.tr_491 to "Márgenes",
    R.string.tr_492 to "Tipografía con serif",
    R.string.tr_493 to "Manga: derecha a izquierda",
    R.string.tr_494 to "Desliza hacia arriba o abajo para leer sin cortes. Los bordes y el selector saltan al inicio de una página. Se guarda el punto dentro de la imagen en este móvil. Para ampliar o usar el efecto Hoja, vuelve a Página completa.",
    R.string.tr_495 to "Puedes ampliar con dos dedos.",
    R.string.tr_496 to "Esperando descarga",
    R.string.tr_497 to "%1\$s/%2\$s páginas o secciones disponibles. %3\$s. No se marca la lectura como terminada.",
    R.string.tr_498 to "Continuar aquí",
    R.string.tr_499 to "Seguir en esta página",
    R.string.tr_500 to "No se pudo abrir esta página",
    R.string.tr_501 to "Se conserva la página anterior y tu progreso. Puedes reintentar el cambio; si persiste, vuelve a descargar este tomo.",
    R.string.tr_502 to "Se sincronizan con Kavita al conectar. Tienen prioridad los cambios de este móvil.",
    R.string.tr_503 to "Se sincronizan con Kavita al conectar. Los conflictos se revisan en Progreso.",
    R.string.tr_504 to "Marcar esta posición",
    R.string.tr_505 to "Todavía no hay marcadores",
    R.string.tr_506 to "Página %1\$s · ",
    R.string.tr_507 to "Otra edición",
    R.string.tr_508 to "Conflicto: revisar en Progreso",
    R.string.tr_509 to "Pendiente de sincronizar",
    R.string.tr_510 to "Sincronizado",
    R.string.tr_511 to "Eliminar marcador %1\$s",
    R.string.tr_512 to "Guardar marcador",
    R.string.tr_513 to "Nombre del marcador",
    R.string.tr_514 to "Lectura completada",
    R.string.tr_515 to "Guardada como leída. ",
    R.string.tr_516 to "Puedes seguir con %1\$s.",
    R.string.tr_517 to "%1\$s no está descargado o cambió de edición. Descárgalo desde Biblioteca para continuar. No se salta ningún tomo.",
    R.string.tr_518 to "Has llegado al final del catálogo guardado de esta obra.",
    R.string.tr_519 to "Continuar lectura",
    R.string.tr_520 to "Volver a la biblioteca",
    R.string.tr_521 to "Quedarme aquí",
    R.string.tr_523 to "Datos restaurados; revisa Progreso antes de sincronizar",
    R.string.tr_524 to "La copia supera el tamaño máximo de 16 MB",
    R.string.tr_525 to "La copia supera 16 MB",
    R.string.tr_526 to "Formato de copia no compatible",
    R.string.tr_527 to "Esta copia pertenece a otro servidor o usuario. Inicia sesión en la cuenta original.",
    R.string.tr_529 to "Cómics",
    R.string.tr_530 to "Libros",
    R.string.tr_531 to "Imágenes",
    R.string.tr_532 to "Novelas ligeras",
    R.string.tr_533 to "Cómics · ComicVine",
    R.string.tr_534 to "Otras lecturas",
    R.string.tr_535 to "Sin leer",
    R.string.tr_536 to "Biblioteca demasiado grande para esta versión",
    R.string.tr_537 to "Selecciona entre 1 y 20.000 unidades de lectura por lote",
    R.string.tr_538 to "No se pudo preparar esta descarga. Comprueba la conexión.",
    R.string.tr_539 to "Inicia sesión",
    R.string.tr_540 to "Activa el permiso Download de tu usuario en Kavita",
    R.string.tr_541 to "Esta lectura no tiene páginas compatibles",
    R.string.tr_542 to "La edición cambió y tienes progreso pendiente. Resuélvelo antes de descargar la nueva edición.",
    R.string.tr_543 to "Cierra esta lectura antes de cambiar de edición",
    R.string.tr_544 to "El archivo cambió en el servidor. Revisa la edición antes de sincronizar.",
    R.string.tr_545 to "Kavita no confirmó la posición enviada",
    R.string.tr_546 to "El archivo cambió en Kavita. La copia offline conserva la edición anterior.",
    R.string.tr_547 to "Todo sincronizado",
    R.string.tr_548 to "Hay progreso pendiente o avisos por revisar",
    R.string.tr_549 to "Sin conexión con Kavita. Progreso guardado en este dispositivo.",
    R.string.tr_550 to "La posición del servidor volvió a cambiar. Revisa el conflicto de nuevo.",
    R.string.tr_551 to " (móvil %1\$s)",
    R.string.tr_552 to "No se pudo consultar Kavita. Se conserva la última copia disponible.",
    R.string.tr_553 to "Listas y colecciones de Kavita",
    R.string.tr_554 to "Consulta del servidor y copia offline de lo que abras. No modifica tus listas online ni las colecciones personales.",
    R.string.tr_555 to "Listas",
    R.string.tr_556 to "Actualizar desde Kavita",
    R.string.tr_557 to "No hay listas disponibles en la copia actual.",
    R.string.tr_558 to "Volver a las listas",
    R.string.tr_559 to "No se pudo eliminar la descarga",
    R.string.tr_560 to "Catálogo de actualizaciones no compatible",
    R.string.tr_561 to "La actualización está incompleta o no coincide con la publicada. Vuelve a descargarla.",
    R.string.tr_562 to "El servidor de actualizaciones no está disponible",
    R.string.tr_563 to "Catálogo vacío",
    R.string.tr_564 to "Descarga vacía",
    R.string.tr_565 to "La descarga supera el tamaño publicado",
    R.string.tr_566 to "No se pudo guardar la actualización",
    R.string.tr_567 to "No se pudo abrir el instalador. Comprueba el permiso o vuelve a descargar la actualización.",
    R.string.tr_568 to "Puedes permitir la instalación y volver a intentarlo cuando quieras.",
    R.string.tr_569 to "Actualizaciones",
    R.string.tr_570 to "Versión instalada · %1\$s",
    R.string.tr_571 to "Nueva versión · %1\$s",
    R.string.tr_572 to "Esta versión necesita un Android más reciente. Puedes seguir usando la versión instalada.",
    R.string.tr_573 to "Lista para instalar. Se conservarán tus descargas, progreso y ajustes.",
    R.string.tr_574 to "Android te pedirá permitir instalaciones desde Troop Reader. Después confirma la actualización en el instalador.",
    R.string.tr_575 to "Abre los ajustes de Android y permite instalar aplicaciones desde Troop Reader.",
    R.string.tr_576 to "Instalar actualización",
    R.string.tr_577 to "Permitir e instalar",
    R.string.tr_578 to "Descargando actualización · %1\$s %",
    R.string.tr_579 to "Se descargará automáticamente en una red Wi‑Fi sin límite de datos.",
    R.string.tr_580 to "Descargar ahora",
    R.string.tr_581 to "Tienes la última versión publicada.",
    R.string.tr_582 to "Consulta si hay una nueva versión de Troop Reader.",
    R.string.tr_583 to "Comprobando · necesita conexión",
    R.string.tr_584 to "Última comprobación: ",
    R.string.tr_585 to "Buscar actualizaciones",
    R.string.tr_586 to "Descargar actualizaciones por Wi‑Fi",
    R.string.tr_587 to "Descarga automática de actualizaciones",
    R.string.tr_588 to "Se buscan al abrir la app y periódicamente en segundo plano. Android puede retrasar la comprobación. La instalación siempre requiere tu confirmación y no interrumpe la lectura.",
    R.string.tr_589 to "Descargar actualización",
    R.string.tr_590 to "Se descargarán %1\$s usando la conexión actual, incluidos datos móviles si no estás en Wi‑Fi.",
    R.string.tr_591 to "Descargar",
    R.string.tr_592 to "Troop Reader · Lectura en voz alta",
    R.string.tr_593 to "Reproduciendo",
    R.string.tr_594 to "En pausa",
    R.string.tr_595 to "Sección %1\$s · %2\$s",
    R.string.tr_596 to "Detener",
    R.string.tr_597 to "Descargas de lectura",
    R.string.tr_598 to "Esperando Wi‑Fi",
    R.string.tr_599 to "En cola",
    R.string.tr_600 to "Descarga pausada. Puedes reanudarla.",
    R.string.tr_601 to "Guardando para leer sin conexión · %1\$s/%2\$s",
    R.string.tr_602 to "Tu usuario necesita permiso de descarga",
    R.string.tr_603 to "El archivo cambió. Elimina la descarga parcial y vuelve a seleccionarlo.",
    R.string.tr_604 to "Número de páginas no compatible",
    R.string.tr_605 to "Descarga automática desactivada",
    R.string.tr_606 to "Límite de descargas automáticas alcanzado. Puedes ampliar el límite o descargar manualmente.",
    R.string.tr_607 to "La sesión cambió",
    R.string.tr_608 to "Límite de descargas automáticas alcanzado",
    R.string.tr_609 to "Kavita no entregó una imagen válida. Reintenta la descarga.",
    R.string.tr_610 to "Descargando %1\$s/%2\$s",
    R.string.tr_611 to "Esperando conexión",
    R.string.tr_612 to "Descarga interrumpida. Comprueba la conexión y reintenta.",
)
